### PR TITLE
restore helm unittests

### PR DESCRIPTION
**Pull request by MichaelSp**
For some reason the unit-tests are quite outdated and are not working anymore. This PR restores the unittests and provides a GitHub Actions workflow to run it on PRs

### CODE REVIEW

**Comment by cfis** [comment]
Cool - happy to have a PR that fixes unit tests, but this PR also includes other additional changes. Could you separate those out? 

Also, what does the `__snapshot__` directory do and why the `snap` file extension after `yaml`?\

**Comment by MichaelSp** [comment]
Additional changes? You mean fixes in [deployment.yaml](https://github.com/docker-mailserver/docker-mailserver-helm/pull/118/files#diff-5bee50a1608fd6f12491184d4be904281fdbd919c80ef4233e903af7772a210f) and typos in values.yaml?

the __snapshots__ will be the generated version that defines the current truth. If you plan to change anything that would change the output, the test will fail because it might be a regression. You can now review the changes in the output of the `helm untittest` run and decide if you want it or not. If you want to continue with the changes you can run `helm unittest -u` to update the snapshots. The files will also be commited in to the repo. The `yaml.snap` files are auto-generated by the tests.
All of that is documented in https://github.com/helm-unittest/helm-unittest

**Comment by cfis** [comment]
Yes, I would like an PR that only contains the changes needed for updating the unit tests. Other changes we can talk about in separate PRs.

Thanks for the explanation on snapshots, that sounds good.

**Comment by cfis** [comment]
Just following up - would like to get this merged.

**Comment by cfis** [comment]
Ping?

**Comment by polarathene** [comment]
Sorry this is a bit off-topic, but just curious @MichaelSp , is SAP using DMS? :)

**Comment by MichaelSp** [comment]
Sorry for the delay here. I couldn't find the time yet to split the PR and timewise it doesn't seem to get any better... (maybe you can accept it in one PR?)

@polarathene AFAIK they are not using DMS 🤣

**Comment by cfis** [comment]
@MichaelSp understood - if I find some time I'll see what I can do.

**Comment by MichaelSp** [comment]
Finally I was able to polish this PR a bit. One thing I noticed:

`readonly` is not a valid param according to the spec https://kubernetes.io/docs/concepts/storage/volumes/. The correct param would be `readOnly`. I assume this field is ignored, but since I assume the state should not be `readOnly`, I took the liberty to remove that.

**Comment by MichaelSp** [comment]
@cfis pong :)

**Comment by cfis** [comment]
Oh sorry, totally missed your last update. Thanks for updating!

**Pull request merged**
