### PR TITLE
Merge FunkyPenguin's Changes

### PR DESCRIPTION
**Pull request by cfis**
This MR rebases funkypenguin's changes (see https://github.com/funkypenguin/helm-docker-mailserver) to the master branch. See https://github.com/docker-mailserver/docker-mailserver-helm/issues/88.

Although there are a lot of commits, in the end only 4 files were changed. The most significant difference is using uppercase ENV variable names that match the names in https://docker-mailserver.github.io/docker-mailserver/latest/config/environment/ (so that seems like a good idea to me).

@funkypenguin   ^^^

### CODE REVIEW

**Comment by funkypenguin** [comment]
Sorry for the delay @cfis, and thank you for persisting here!

**Comment by funkypenguin** [comment]
The chart wants a semver version bump (in `Chart.yaml`) before linting will pass it :)

**Comment by cfis** [comment]
Done. I also went ahead and updated the appVersion to 13.2.0 as well as the dockermailer image tag.

For the chart version I set it to 2.2.0, but I can see an argument to 3.0.0 due to the changes in the ENV variables. Let me know what you prefer.

And no worries, you are the one who did all the work!

**Comment by cfis** [comment]
Hi @funkypenguin  - just wanted to follow up on this MR.

Also, I have a some more significant updates to the repo which I would love to merge in (see https://github.com/cfis/docker-mailserver-helm/commits/master/). Not sure if you have time to review them, or if someone else could? Or I'm happy to merge in if you allow me write access.

Thanks - Charlie!

**Comment by cfis** [comment]
Fyi - https://github.com/docker-mailserver/docker-mailserver/issues/3825

**Comment by georglauterbach** [comment]
Linting seems to fail still; can and will this be fixed? The changes look good!

@cfis we lack maintainers for the chart. Are you interested in joining the maintainer's team for the chart repository? This way, you can delelop on this more easily and merge smaller PRs yourself. Moreover, you could review and merge PRs from other contributors.

**Comment by cfis** [comment]
Yes, will fix linting. And happy to join maintainers list - thanks!

**Comment by cfis** [comment]
Linting should be fixed (tested locally).

**Comment by georglauterbach** [comment]
I sent you an invitation @cfis. When you accept, you should be able to merge this PR, as I will approve this PR in a second. What would be ideal is a fix of the CI (`chart-testing` seems to be broken) and merging the now-stale PRs in this repository :) Feel free to tackle these tasks 🚀

**Review by georglauterbach — APPROVED** [review]

**Pull request merged**
