### PR TITLE
Restart pod when deploying with changes to configmap.yaml

### PR DESCRIPTION
**Pull request by abh**

### CODE REVIEW

**Comment by abh** [comment]
It seemed rude to bump the chart version number unless you think it's appropriate that each change would just be a new release. Maybe that's not so crazy. 🤷

**Comment by funkypenguin** [comment]
As I understand it, that's best-practice, so go ahead and bump the chart (semver) version for each change ;)

**Comment by abh** [comment]
Bumped the chart version. Since you already have two branches going effectively I did the later one. Should I make the PR against your personal repository instead?

**Comment by abh** [comment]
ah, never mind. Here's a clean version against the org version. :-)

**Comment by funkypenguin** [comment]
Thanks @abh ... Since I started using flux to manage my deployments, I'm no longer a fan of the checksum-based approach, since when certain automation (like flux) is used, it generates unnecessary deployment restarts (_see https://github.com/minio/minio/pull/14396 for a similar issue_).

I'd rather support the ability of the operator to specify custom deployment annotations (see `deployment.annotations`), and then rely on something like https://github.com/stakater/Reloader to trigger the deployment restarts. Perhaps adding this to the existing documentation could be a new repo issue?

Cheers!
D

**Pull request closed without merging**
