### PR TITLE
various cleanups

### PR DESCRIPTION
**Pull request by rspier**
update dockerhub URLs from https://hub.docker.com/r/tvial/docker-mailserver to https://hub.docker.com/r/mailserver/docker-mailserver
improvements to GitHub Actions for CI, including parallelism and making it work consistently with v1.20

### CODE REVIEW

**Review by funkypenguin — APPROVED** [review]
Thanks for the detail-oriented fix @rspie!

**Comment by funkypenguin** [comment]
Please bump version in `Chart.yaml` so that ct-lint will be happy, @rspier  :)

**Comment by rspier** [comment]
The integration tests are failing, in a way that I'm 99.99% sure is not related to the content of the PR.

```
  Warning  FailedScheduling  1s (x6 over 5m)  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
```

Looking deeper at the logs, I think the test "cluster" just isn't coming up fast enough and it times out.

I'll keep digging, time permitting.

**Comment by rspier** [comment]
It works with a newer version of kind. Right now that's in this PR, would you like me to split it to its own PR? Or its own commit?

**Comment by rspier** [comment]
I'm going to split this into multiple commits.  Stay tuned!

**Comment by rspier** [comment]
Ok, I think I'm done.  :)  Please take another look.

**Pull request merged**
