### PR TITLE
Added initContainers

### LINKED ISSUE #114: Could not mount multiple keys from same ConfigMap or Secret
Hi,

Currently `configMaps` and `secrets` format only support one key to be mount.

I would like to mount multiple keys from the same ConfigMap or Secret.

Futhermore I could not set :

- volume defaultMode
- volumeMount readOnly

I'm able to create a PR but this will break the current format ?

Best regards,
Guillaume

### PR DESCRIPTION
**Pull request by johnstarxx**
Added `initContainers` (with `extraVolumes` and `extraVolumeMounts` fields). Also closes: #114.

These fields are need if for example one uses custom CA authority (Step Certificates) and needs to set a custom certificate that needs to be stored in `/etc/ssl/certs/`. Using an init container, one can mount the certificates to the given folder and run the `update-ca-certificates` command.

### CODE REVIEW

**Comment by cfis** [comment]
For extra volumes, could we just use the already existing persistence key?

**Comment by johnstarxx** [comment]
Using `extraVolumes` is more flexible because it allows mounting any type of volume (e.g., `emptyDir`, `downwardAPI`, `projected`). In my use case, the custom CA certificates are generated at runtime by an `initContainer` and only need to be available for the lifecycle of the pod, so persistence is not required. This simplifies configuration and ensures up-to-date certificates.

**Comment by cfis** [comment]
Ok, does this PR work?

https://github.com/docker-mailserver/docker-mailserver-helm/pull/117

So then this one would just be for initcontainers (which matches the subject name).

**Comment by johnstarxx** [comment]
Yes, I think it might work. The difference between the two is that in PR #117 the extraVolume(s/Mounts) are in the `.Values`, whereas in this PR they are in the `.Values.deployment` like in other charts (e.g. [argo](https://github.com/argoproj/argo-helm/blob/ea28da27d14035f9efa88750a45b1fdf21585ec0/charts/argo-cd/values.yaml#L1863) or [cert-manager](https://github.com/cert-manager/cert-manager/blob/659f22bf7ed15ab37dc94f3b714818924e83de3c/deploy/charts/cert-manager/values.yaml#L1162C1-L1162C3 )). There are also charts that use them directly from `.Values` ([prometheus-adapter](https://github.com/prometheus-community/helm-charts/blob/5dcc890bbb5cb1d8c952835067332e39efec0ca4/charts/prometheus-adapter/values.yaml#L235)) it they know that there will be only one deployment).

**Comment by cfis** [comment]
I see. Thanks!

**Pull request merged**
